In [2]:
# work with csv data

import pandas as pd

In [6]:
df = pd.read_csv("employee_data.csv")
print(df)

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

Data Frame Methods

In [ ]:
df.head() # gives iniial 5 rows 
df.tail() # gives end 5 rows

df.sample(3) # gives a random row or gives n row when passed n as attribute
df.info() # gives the summary of data

df.shape # gives a tupple of ( row , col)

df.describe() #gives the summary for numerical col

df.columns # gives all the coloumns

df.nunique() # gives all the unique row

Work with kaggle data set

In [33]:
df = pd.read_csv("globalAirQuality.csv")


aqi_val = 100
df.query("aqi >@aqi_val & temperature >25")[["city" ,"aqi"]]

           city  aqi
6      New York  155
7      New York  115
13     New York  124
14     New York  121
17     New York  127
...         ...  ...
17970    Zurich  141
17975    Zurich  111
17976    Zurich  146
17991    Zurich  104
17996    Zurich  105

[3850 rows x 2 columns]

In [46]:
# Cleaning data - Handling the missing vlues

df = pd.read_csv("raw_data.csv")
df.isnull() 

df.isnull().sum()

df.dropna(axis=1)


df.fillna(0)

copied_data = df.copy()

copied_data.ffill()

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  29.0  Canada   Female  62000.0
3    3          Alex  29.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female  47000.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6        Li Wei  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0   India     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  29.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA     Male  58000.0

In [47]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [49]:
#Handling the duplicates 

df.duplicated()

0     False
1      True
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
dtype: bool